repository: Harmontown/harmontown.github.io
theme: jekyll-theme-leap-day
url: https://harmontown.github.io
plugins:
- jekyll-sitemap
- jekyll-seo-tag
incremental: true

title: Harmontown Podcast Wiki
description: from Anastasia to Zardoz
show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]

collections:
  episodes:
    output: true
    sort_by: sequenceNumber

exclude:
  - .sass-cache

strict_front_matter: true

github:
  owner_url: https://github.com/stubn0rtz
  owner_name: Stubn0rtz

# lastUpdated: '2023-03-11 02:54:46 +0000'
# commit: 43045fd
