name: Build and deploy jekyll site

on:
  push:
    branches:
      - main
      - actions-testing
      # - source
      # It is highly recommended that you only run this action on push to a
      # specific branch, eg. master or source (if on *.github.io repo)

permissions:
  contents: write

jobs:
  jekyll-build:
    runs-on: ubuntu-22.04
    steps:
      - name: 📂 checkout
        uses: actions/checkout@v3

      - name: 🔨 build
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "docker-compose.yml"
          up-flags: --abort-on-container-exit

      - name: 🧞 grant necessary filesystem access
        run: chmod 0777 ./docs

      - name: 🐞 debug - list files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.1
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: "."
          ext: ".html"

      - name: 🚀 deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site
          enable_jekyll: false
