name: Build and deploy jekyll site

on:
  push:
    branches:
      - main
      - actions-testing
      # - source
      # It is highly recommended that you only run this action on push to a
      # specific branch, eg. master or source (if on *.github.io repo)

permissions:
  contents: write

jobs:
  jekyll-build:
    runs-on: ubuntu-22.04
    steps:
      - name: 📂 checkout
        uses: actions/checkout@v3

      - name: 🧞 grant necessary filesystem access
        run: chmod 0777 ./docs

      - name: 🦶 populate footer data
        run: |
          echo -e "\n" >> ./docs/_config.yml
          echo -e "commit: $(echo ${{ github.sha }} | cut -c1-7)" >> ./docs/_config.yml
          echo -e "\n" >> ./docs/_config.yml
          echo -e "lastUpdated: '${{ github.event.repository.updated_at }}'" >> ./docs/_config.yml

      - name: 🔨 build
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "docker-compose.yml"
          up-flags: --abort-on-container-exit

      - name: 🚀 deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site
          enable_jekyll: false
